### PR TITLE
Solutions for first week in Julia

### PR DESCRIPTION
**Pull request by jhlq**
Have written a package for symbolic computation in Julia and it is helping to solve the assignments, so far the result is 100% in terms of points. Would be lovely if people could try the package since it is still in alpha state and needs testers.

A html version of the notebook is here: http://artai.co/Plasma.html

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Wouldn't it be better to just post on the forums instead of putting it here?

**Comment by jhlq** [comment]
Will post it on the forums, is there any reason not to have it here also? Then people who miss the post can still find it if they check the repo.

**Comment by StanczakDominik** [comment]
Yeah I guess, though I'd imagine it's much less likely that people are going to check the repository! Besides, I'd imagine the staff might pin this up if you ask them. But sure, we can stick it up here.

**Comment by StanczakDominik** [comment]
I guess we could also include a link to your solutions in the title page of the notes' pdf file? What do you think?

**Comment by jhlq** [comment]
Yeah a general link to Julia and the Equations repo https://github.com/jhlq/Equations.jl as an alternative to matlab would be great. The solutions are meant as working examples of how to get the package going and wont aim for complete coverage of every course task, for example week 2 was more about numerics and clever thinking than deriving equation relations.

**Comment by StanczakDominik** [comment]
Care to formulate that however you'd like? You're the Julia expert between the two of us ;)

**Comment by jhlq** [comment]
Started on a PR but to compile the pdf almost a GB has to be downloaded and the internet here is not so good, would be easier if you could add to the file:

"Julia along with the Equations package can be used as an open source alternative to Matlab.
Official Julia website: http://julialang.org/
Equations repository: https://github.com/jhlq/Equations.jl
To install the package type, inside Julia: Pkg.clone("https://github.com/jhlq/Equations.jl")
Example use in the form of solutions to course assignments is available in notebook format in the PlasmaXNotes repository, in the examples directory of Equations and as a html at http://artai.co/Plasma.html
The Equations package is currently in a developing stage so please submit any encountered issues."

**Comment by StanczakDominik** [comment]
Yeah don't worry about compiling it, I've got that covered. :)

**Comment by jhlq** [comment]
Great! Have made a forum post: https://courses.edx.org/courses/course-v1:EPFLx+PlasmaX+2T2015/discussion/forum/i4x-EPFL-PlasmaX-course-1-a/threads/5557861fe2acfeb52500145d

**Pull request merged**
